"""What the shell offers when an operator presses tab.

The values the CLI takes are not guessable — 38 game ids, whatever plugins are bundled and installed,
a config path per server — and until now the only way to see them was `b3 games`, `b3 plugins`, or the
source. This is the same discovery at the prompt.

**The logic lives here rather than in the shell layer**, and that is the whole design: a completer is
a function from a prefix to a list of candidates, which is testable without a terminal. The shell side
is `argcomplete`, one dependency, chosen deliberately over hand-rolling per-shell scripts — see
`b3 completion` in the CLI for what an operator has to add to their shell.

Two facts about `argcomplete` that decided how this is wired, both established by reading 3.7.2 rather
than assumed:

* **Per-command registration works from anywhere.** `register-python-argcomplete b3` emits a shell
  function that runs *the command as typed* with `_ARGCOMPLETE=1` and file descriptors 8 and 9
  redirected. It never opens the script file, so a console script inside a virtualenv symlinked onto
  `PATH` — the layout `docs/deployment.md` recommends, and the one where completion most often
  silently does not work — completes normally.
* **Global completion is the part that cannot be promised.** That path scans the executable's first
  1024 bytes for a `PYTHON_ARGCOMPLETE_OK` marker, and a console script is generated by pip, not by
  us, so the marker cannot be put there. The marker at the top of `b3.cli` covers
  `python -m b3.cli`; for the installed `b3`, per-command registration is the supported answer.

Every completer takes argcomplete's keyword arguments (`action`, `parser`, `parsed_args`) and ignores
them, so it is an ordinary function anything else can call.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

#: Directory names never worth offering as a place a config lives.
SKIP_DIRS = frozenset({"__pycache__", ".git", ".venv", "venv", "node_modules", ".mypy_cache"})

#: What a config file is called. `b3 -c` takes a path, and offering every file in a directory would
#: bury the one file being looked for.
CONFIG_SUFFIXES = (".yaml", ".yml")


def games(prefix: str = "", **_: Any) -> list[str]:
    """Every game id, which is what `server.game` and `b3 init --game` take.

    Read from the profile table, so a title added tomorrow completes without anybody remembering.
    """
    from b3.parsers.games import PROFILES

    return sorted(name for name in PROFILES if name.startswith(prefix))


def plugins(prefix: str = "", **_: Any) -> list[str]:
    """Plugins this machine could run: the bundled ones, plus anything git-installed.

    Both pools, because `b3 plugin enable` accepts either and an operator who installed a plugin for
    one server wants to see it when enabling it on another.
    """
    names = set(bundled())
    for directory in _installed_dirs():
        names.update(_plugin_names_in(directory))
    return sorted(name for name in names if name.startswith(prefix))


def bundled(prefix: str = "", **_: Any) -> list[str]:
    """The plugins that ship with the bot, read from the package rather than from a list."""
    package = Path(__file__).resolve().parent.parent / "plugins"
    return sorted(name for name in _plugin_names_in(package) if name.startswith(prefix))


def installed(prefix: str = "", **_: Any) -> list[str]:
    """Only the git-installed plugins, for `b3 plugin remove`.

    Not the bundled ones, which is the difference from `plugins()`: `remove` uninstalls from the pool
    and refuses a name that was never installed, so offering `admin` there would be offering a name
    the command exists to reject.
    """
    names: set[str] = set()
    for directory in _installed_dirs():
        names.update(_plugin_names_in(directory))
    return sorted(name for name in names if name.startswith(prefix))


def configs(prefix: str = "", **_: Any) -> list[str]:
    """Config files and the directories that might hold one, for `b3 -c`.

    Directories are offered with a trailing separator so a second tab walks into them, which is what
    makes `-c /srv/<tab>` useful on the layout where every server has its own directory.
    """
    expanded = os.path.expanduser(prefix)
    directory = Path(expanded).parent if not expanded.endswith(("/", os.sep)) else Path(expanded)
    stem = "" if expanded.endswith(("/", os.sep)) else Path(expanded).name
    try:
        entries = sorted(Path(directory or ".").iterdir())
    except OSError:
        return []
    out: list[str] = []
    for item in entries:
        if not item.name.startswith(stem) or item.name in SKIP_DIRS:
            continue
        shown = str(item)
        if item.is_dir():
            out.append(shown + os.sep)
        elif item.suffix.lower() in CONFIG_SUFFIXES:
            out.append(shown)
    return out


def revisions(prefix: str = "", **_: Any) -> list[str]:
    """Migration revisions, for `b3 db --revision`.

    Read out of the packaged migration scripts, which needs no database — the point being that this
    completes on an install whose database is unreachable, which is exactly when somebody is typing a
    revision by hand.
    """
    scripts = Path(__file__).resolve().parent.parent / "storage" / "migrations" / "versions"
    found = {"head", "base"}
    try:
        for item in scripts.glob("*.py"):
            found.add(item.name.split("_", 1)[0])
    except OSError:  # pragma: no cover - a packaged directory that is not there
        pass
    return sorted(name for name in found if name.startswith(prefix))


def _installed_dirs() -> list[Path]:
    """Where git-installed plugins live, for both pools, without needing a config.

    A completer runs on every tab press, so this must not read or validate a config file: the answer
    is "what is on this machine", and the two conventional locations are enough for that.
    """
    here = Path.cwd()
    return [here / "conf" / "plugins", here / "plugins"]


def _plugin_names_in(directory: Path) -> list[str]:
    try:
        items = sorted(directory.iterdir())
    except OSError:
        return []
    return [
        item.name
        for item in items
        if item.is_dir() and item.name not in SKIP_DIRS and (item / "__init__.py").is_file()
    ]


__all__ = ["bundled", "configs", "games", "installed", "plugins", "revisions"]
