# PYTHON_ARGCOMPLETE_OK
"""Command-line entrypoint: ``b3 run`` (live) and ``b3 replay`` (offline).

The marker on the first line is argcomplete's: it is what lets *global* completion recognise
``python -m b3.cli`` as completable. The installed `b3` console script is generated by pip rather than
by us, so the marker cannot be put in that file — which is why `b3 completion` recommends per-command
registration, the form that works regardless. See `b3.core.completion`.
"""

from __future__ import annotations

import argparse
import asyncio
import logging
import subprocess
import sys
import time
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

from typing import Protocol, runtime_checkable

from b3 import __version__
from b3.config.loader import load_config
from b3.config.schema import Config
from b3.core import completion
from b3.core.instance import RESTART_EXIT_CODE, InstanceSpec
from b3.net.logsource import LogSource
from b3.runtime.bot import Bot, RconClient


@runtime_checkable
class PushClient(RconClient, LogSource, Protocol):
    """A client for an engine that *pushes* its events down the RCON connection.

    Both halves of the bot's input in one object, stated in the type system rather than left as a
    comment: BattlEye and Frostbite have no game log, so their RCON client is also their log source.
    """


def build_bot(
    config: Config,
    *,
    rcon: RconClient | None = None,
    conf_dir: Path | None = None,
    config_path: str = "",
) -> Bot:
    """Build a bot with the plugins listed in the config, loaded in dependency order."""
    from b3.core.plugininstall import installed_plugins_dir, register_installed_plugins
    from b3.core.pluginmgr import load_plugins

    # Git-installed plugins live outside the package tree; make them importable before resolving.
    # This server's own directory is registered last so it lands first on sys.path: if the same
    # plugin exists in both, the copy this server installed for itself wins over the shared pool.
    if config.bot.shared_plugins_dir:
        register_installed_plugins(installed_plugins_dir(config.bot.shared_plugins_dir, conf_dir))
    register_installed_plugins(installed_plugins_dir(config.bot.plugins_dir, conf_dir))

    bot = Bot(config, rcon=rcon)
    # Before the plugins load, not after. A plugin resolving `@conf` in its own settings asks the bot
    # for this path, and a bot that does not know yet falls back to the working directory — so
    # banlist looked for its list files wherever the operator happened to `cd` from, and said it
    # could not read them.
    bot.config_path = Path(config_path) if config_path else None
    for loaded in load_plugins(bot, config, conf_dir=conf_dir):
        bot.add_plugin(loaded.plugin, loaded.name)
    bot.start()
    return bot


#: How often the live loop comes round: fast enough for a local tail and for scheduler ticks.
LIVE_TICK = 0.2

#: Shells `b3 completion` can print a registration for. Every one of these is argcomplete's — this
#: bot writes no completion scripts of its own, which is the whole reason for taking the dependency.
#: PowerShell is on the list because argcomplete 3.x registers a native `ArgumentCompleter` for it;
#: it was not always so, and this project's own notes said Windows had no answer.
SHELLS = ("bash", "zsh", "fish", "tcsh", "powershell")

#: Commands that say nothing about updates when they finish. `update`, `version` and `doctor` each
#: report the same thing themselves and would say it twice; `run` logs it on its own schedule while
#: it runs; `completion` writes a shell snippet somebody pastes, and a stray line in it is a syntax
#: error in their shell rc.
NO_UPDATE_NOTICE = frozenset({"update", "version", "doctor", "completion", "run"})


def _autocomplete(parser: argparse.ArgumentParser) -> None:
    """Let the shell ask this parser what comes next, if argcomplete is installed.

    A no-op otherwise, and silent about it: a bot whose CLI refused to run without a completion
    library would be a poor trade for tab completion.
    """
    try:
        import argcomplete
    except ImportError:
        return
    argcomplete.autocomplete(parser)


def _run_completion(shell: str) -> int:
    """`b3 completion [shell]` — print what to add to a shell so tab completion works.

    Printed rather than installed. Editing somebody's shell configuration behind their back is not
    something a game-server bot should do, and every shell here has its own file with its own
    conventions; one line an operator can read and paste is both smaller and honest.
    """
    guessed = shell or _guess_shell()
    try:
        from argcomplete.shell_integration import shellcode
    except ImportError:
        print("tab completion needs argcomplete, which is an optional extra:")
        print("    pip install 'b3ng[completion]'")
        print("then run this command again.")
        return 1
    if not guessed:
        print(f"name a shell: {', '.join(SHELLS)}")
        return 1
    if guessed not in SHELLS:
        print(f"{guessed}: no completion for that shell. Known: {', '.join(SHELLS)}")
        return 1
    where = {
        "bash": "~/.bashrc",
        "zsh": "~/.zshrc",
        "fish": "~/.config/fish/completions/b3.fish",
        "tcsh": "~/.cshrc",
        "powershell": "your $PROFILE",
    }[guessed]
    print(f"# Add this to {where}, then start a new shell:")
    # argcomplete's own generator, so the mechanics stay its problem and not ours. `use_defaults`
    # off: we ask for exactly the completers this parser declares rather than argcomplete's guesses
    # about files, which would offer every file in the directory for `--game`.
    print(shellcode(["b3"], use_defaults=False, shell=guessed).strip())
    return 0


def _guess_shell() -> str:
    """Which shell asked, from the environment. "" when there is nothing to go on.

    A guess, and the message says so by printing the name it guessed — an operator pasting a bash
    snippet into zsh would otherwise be left wondering why nothing completes.
    """
    import os
    import platform

    if platform.system() == "Windows" and not os.environ.get("SHELL"):
        return "powershell"
    name = Path(os.environ.get("SHELL", "")).name.lower()
    # Git Bash on Windows reports `/bin/bash.exe`, and a guess that fails there fails on the platform
    # least likely to have a shell rc set up already.
    name = name.removesuffix(".exe")
    return name if name in SHELLS else ""


@dataclass(slots=True)
class Connection:
    """How the bot reaches one game server: a way to command it, and a way to hear from it.

    ``shared`` says the two are the same object, which is the case for an engine that pushes its
    events down the RCON socket (BattlEye). Stated as a flag rather than left to an identity check,
    because "is this rcon client also the log source?" is a fact about the *engine*, and reading it
    off `is` invites the reader to think it might be an accident.
    """

    rcon: RconClient
    source: LogSource
    description: str
    shared: bool = False


def _connect(config: Config) -> Connection:
    """Build this game's RCON client and event source.

    For most games these are two independent things: a UDP RCON socket, and a log file (local or
    remote) to tail. A BattlEye game has no log at all — its RCON socket *is* the event stream — so
    there the two are one object, and `server.game_log` is ignored. Deciding that here keeps
    `_run_live` below identical for both, which is the point: the loop should not know.
    """
    from b3.net.logsource import create_log_source
    from b3.net.rcon import Rcon, UdpRconTransport, dialect_for
    from b3.parsers.games import (
        FILE_RCON_FAMILIES,
        PUSH_FAMILIES,
        TCP_RCON_FAMILIES,
        profile_for,
    )

    # Raises UnknownGameError on a typo, which main() reports; nothing has connected yet.
    profile = profile_for(config.server.game)

    if profile.family in FILE_RCON_FAMILIES:
        # A third shape: the events come from a log like most games, but commands are *appended to a
        # file* the game server reads rather than sent over a socket. Altitude has no admin port.
        return Connection(
            rcon=_command_file_client(config),
            source=create_log_source(
                config.server.game_log,
                # utf-8 regardless of `server.encoding`, which defaults to latin-1 for the CoD
                # engines. This log is JSON, and JSON is UTF-8 by definition — reading it as
                # latin-1 does not fail, it just quietly mangles every non-ASCII player name. The
                # source decodes with errors="replace", so a stray byte still costs one character
                # rather than the line.
                encoding="utf-8",
                poll_interval=config.server.log_poll_interval,
                timeout=config.server.log_timeout,
                max_gap=config.server.log_max_gap,
            ),
            description=f"{config.server.game_log} (commands -> {config.server.command_file})",
        )

    if profile.family in PUSH_FAMILIES:
        # An engine that pushes its events: one object is both halves. Which one it is remains the
        # profile's business, not the loop's.
        pushers: dict[str, Callable[[Config], PushClient]] = {
            "battleye": _battleye_client,
            "frostbite": _frostbite_client,
            "homefront": _homefront_client,
            "ravaged": _ravaged_client,
            "frontline": _frontline_client,
        }
        client = pushers[profile.family](config)
        return Connection(
            rcon=client,
            source=client,
            description=(
                f"{config.server.host}:{config.server.port} ({profile.family} rcon, events pushed)"
            ),
            shared=True,
        )

    if profile.family in TCP_RCON_FAMILIES:
        # A fourth shape: events from a log file like most games, but a *stateful* rcon — a TCP
        # session with a login handshake, which cannot be expressed as one of `Rcon`'s dialects
        # because those encode a password into every datagram and this one authenticates once.
        return Connection(
            rcon=_source_client(config),
            source=create_log_source(
                config.server.game_log,
                # utf-8 regardless of `server.encoding`, which defaults to latin-1 for the Call of
                # Duty engines. A Source server writes utf-8, so reading it as latin-1 does not fail
                # — it quietly mangles every non-ASCII player name, and a mangled name is a name no
                # `!ban` will match.
                encoding="utf-8",
                poll_interval=config.server.log_poll_interval,
                timeout=config.server.log_timeout,
                max_gap=config.server.log_max_gap,
            ),
            description=(
                f"{config.server.game_log} (commands -> {config.server.host}:"
                f"{config.server.port} source rcon)"
            ),
        )

    transport = UdpRconTransport(
        config.server.host, config.server.port, timeout=config.server.rcon_timeout
    )
    rcon = Rcon(
        transport,
        password=config.server.rcon_password,
        encoding=config.server.encoding,
        # Black Ops frames its packets differently; every other title speaks plain Quake3.
        dialect=dialect_for(profile.rcon_dialect),
    )
    source = create_log_source(
        config.server.game_log,
        encoding=config.server.encoding,
        poll_interval=config.server.log_poll_interval,
        timeout=config.server.log_timeout,
        max_gap=config.server.log_max_gap,
    )
    return Connection(rcon=rcon, source=source, description=config.server.game_log)


def _command_file_client(config: Config) -> RconClient:
    """The Altitude "rcon": a file the game server reads commands out of.

    Refuses to build without ``server.command_file``. The classic parser died here too, and it is the
    right call: every admin command — every kick, ban and reply — would otherwise be written nowhere
    and report success. A bot that cannot act is not a working bot, and finding out from a player is
    the expensive way.
    """
    from b3.config.schema import ConfigError
    from b3.net.altitude import AltitudeCommandFile

    if not config.server.command_file:
        raise ConfigError(
            f"{config.server.game} is commanded through a file, so server.command_file must be set "
            "(it is the command.txt the game server reads; see `b3 doctor`)"
        )
    client = AltitudeCommandFile(
        config.server.command_file, port=config.server.port, encoding="utf-8"
    )
    client.open()
    return client


def _source_client(config: Config) -> RconClient:
    """Source RCON, opened and authenticated before the bot is handed it.

    Opened here rather than lazily so a wrong password is reported by `b3 run` at startup, next to the
    line that says which server it is, instead of at whatever moment the first command happens to be
    sent — which on a quiet server could be the first `!kick`, hours later.
    """
    from b3.net.source import SourceRconClient

    client = SourceRconClient(
        config.server.host,
        config.server.port,
        config.server.rcon_password,
        timeout=max(config.server.rcon_timeout, 2.0),
        # utf-8 for the same reason the log is read as utf-8: it is what this protocol carries, and
        # `server.encoding` describes the Call of Duty engines rather than this one.
        encoding="utf-8",
    )
    client.open()
    return client


def _battleye_client(config: Config) -> PushClient:
    from b3.net.battleye import BattleyeClient

    return BattleyeClient(
        config.server.host,
        config.server.port,
        config.server.rcon_password,
        timeout=config.server.rcon_timeout,
    )


def _frostbite_client(config: Config) -> PushClient:
    from b3.net.frostbite import FrostbiteClient
    from b3.parsers.frostbite.profiles import ALL as FROSTBITE_PROFILES
    from b3.parsers.frostbite.profiles import LEGACY_MAPLIST

    profile = FROSTBITE_PROFILES.get(config.server.game)
    return FrostbiteClient(
        config.server.host,
        config.server.port,
        config.server.rcon_password,
        timeout=config.server.rcon_timeout,
        # Two per-title things this layer needs. Bad Company 2 and the 2010 Medal of Honor keep a
        # flat map list, where the four Frostbite 2 titles keep (map, gamemode, rounds) entries; the
        # two generations also differ in how fast their chat area can be read (the classic paced
        # Frostbite 1 at 2s and Frostbite 2 at 0.8s), and both follow from this one flag.
        legacy_maplist=config.server.game in LEGACY_MAPLIST,
        # And the verb that moves the game on, which is the last step of loading a named map. Three
        # spellings across the six titles, so it comes from the profile rather than from the flag.
        rotate_command=profile.rotate_command if profile else "",
    )


def _homefront_client(config: Config) -> PushClient:
    from b3.net.homefront import HomefrontClient

    return HomefrontClient(
        config.server.host,
        config.server.port,
        config.server.rcon_password,
        timeout=config.server.rcon_timeout,
    )


def _frontline_client(config: Config) -> PushClient:
    from b3.net.frontline import FrontlineClient

    return FrontlineClient(
        config.server.host,
        config.server.port,
        config.server.rcon_password,
        # This engine authenticates a user as well as a password, and cannot log in without one.
        user=config.server.rcon_user,
        timeout=max(config.server.rcon_timeout, 1.0),
    )


def _ravaged_client(config: Config) -> PushClient:
    from b3.net.ravaged import RavagedClient

    return RavagedClient(
        config.server.host,
        config.server.port,
        config.server.rcon_password,
        # Its `LOGIN=` step names an account too, and a server whose admin is not called "admin"
        # would otherwise be unreachable with no way to say so in the config.
        user=config.server.rcon_user,
        # A longer floor than the rcon default: this engine answers questions, and a player-list
        # round trip on a busy server is not instant.
        timeout=max(config.server.rcon_timeout, 2.0),
    )


def _supervise() -> int:
    """Run the bot in a child process, and start it again when `!restart` stops it.

    `!restart` sets exit code 221 and stops; **it does not re-exec**, and that is deliberate - a
    process that replaces itself in place is how the classic bot leaked file handles and RCON
    sockets. The classic solved the other half by shipping a launcher (`b3/run.py`) that ran the bot
    as a subprocess and started it again on 221, and this is that launcher: one flag rather than a
    second script, so `!restart` works for somebody who is simply running `b3 run` in a terminal.

    Under systemd, Docker or any supervisor, do not use this: `Restart=on-failure` already does it,
    and two things restarting one bot is one too many.

    The child is the same command line minus this flag - taken from `sys.orig_argv`, so it works
    whether the bot was started through the `b3` console script or as `python -m`.
    """
    child = [arg for arg in sys.orig_argv if arg != "--supervise"]
    restarts = 0
    while True:
        status = subprocess.call(child)
        if status != RESTART_EXIT_CODE:
            if restarts:
                logging.info("b3 stopped with exit code %d after %d restart(s)", status, restarts)
            return status
        restarts += 1
        logging.info("b3 asked to restart (%d); starting it again", restarts)


async def _run_live(
    config: Config,
    conf_dir: Path | None = None,
    config_path: str = "",
    *,
    allow_schema_drift: bool = False,
) -> int:
    if not allow_schema_drift and _refuse_on_schema_drift(config, config_path):
        return 1
    connection = _connect(config)
    rcon, source = connection.rcon, connection.source
    # `config_path` is also what `!reconfig` re-reads.
    bot = build_bot(config, rcon=rcon, conf_dir=conf_dir, config_path=config_path)

    from b3.net.logsource import LogSourceError

    try:
        source.open()
    except (OSError, LogSourceError) as exc:
        # The commonest first-run failure of all: a game log that is not where the config says. It
        # used to be a traceback — and because this open sat outside the block below, whatever
        # `_connect` had already built was never closed either.
        logging.error("cannot read %s: %s", connection.description, exc)
        logging.error(
            "-> check server.game_log, then run `b3 -c %s doctor` for the whole picture",
            config_path or "b3.yaml",
        )
        try:
            rcon.close()  # closes the source too on an engine where they are one object
        except Exception:  # noqa: BLE001 - nothing useful to do while giving up
            pass
        return 1

    logging.info("b3 running; reading %s", connection.description)
    # And say so in the game, as the classic bot did from `parser.start()`. On a server whose
    # players know what b3 is, this is how they learn it is watching again after a restart - and
    # after `!restart` it is the only confirmation that the bot came back at all. An operator who
    # would rather it stayed quiet sets `b3_online` to nothing.
    online = bot.messages.get("b3_online", name=config.bot.name, version=__version__)
    if online.strip():
        bot.say(online)
    next_poll = 0.0
    try:
        while bot.exit_code is None:
            now = time.monotonic()
            if now >= next_poll:
                next_poll = now + source.poll_interval
                # Remote sources block on network I/O; keep them off the event loop thread.
                lines = (
                    await asyncio.to_thread(source.read_lines)
                    if source.blocking
                    else source.read_lines()
                )
                for line in lines:
                    await bot.feed_line(line)
            # Timed plugin work (b3.core.scheduler); ticks are deduped to once per second.
            await bot.scheduler.tick()
            await asyncio.sleep(LIVE_TICK)
        # `!die` (0) or `!restart` (221 — the classic code a supervisor script watches for).
        logging.info("stopping with exit code %d", bot.exit_code)
        return bot.exit_code
    finally:
        # Before the socket goes: a pending auth poll would otherwise wake up and query an rcon
        # that has been closed under it.
        bot.auth.cancel_all()
        source.close()
        if not connection.shared:  # on a BattlEye game those were the same socket
            rcon.close()


async def _run_replay(
    config: Config, logfile: str, conf_dir: Path | None = None, config_path: str = ""
) -> None:
    from b3.net.logsource import FileLogSource

    bot = build_bot(config, conf_dir=conf_dir, config_path=config_path)  # no rcon in replay mode
    source = FileLogSource(logfile, encoding=config.server.encoding, from_start=True)
    source.open()
    lines = source.read_lines()
    source.close()
    await bot.replay(lines)
    logging.info("replayed %d lines from %s", len(lines), logfile)


def build_parser() -> argparse.ArgumentParser:
    """Every command, flag and completer the CLI has.

    Built in its own function rather than inside `main` so the shell can be handed the same
    parser an operator gets: a completer attached to the wrong object completes nothing and says
    nothing about it, and the only way to catch that is to ask this parser what it would offer.
    """
    from b3.core.probe import DEFAULT_LINES
    from b3.parsers.games import PROFILES

    parser = argparse.ArgumentParser(prog="b3", description="Big Brother Bot 2.0")
    config_arg = parser.add_argument(
        "-c", "--config", default="b3.yaml", help="path to the YAML config"
    )
    config_arg.completer = completion.configs  # type: ignore[attr-defined]
    parser.add_argument("-v", "--verbose", action="store_true")
    # The first thing anybody types. `b3 version` says more — it also names the latest release — but
    # the flag has to exist, because a tool that answers `--version` with a usage error looks broken.
    parser.add_argument("--version", action="version", version=f"b3 {__version__}")
    sub = parser.add_subparsers(dest="cmd", required=True)
    run = sub.add_parser("run", help="connect to the server and run")
    # An operator who knows their database is fine — a shared one another bot has already upgraded,
    # say — can say so. Named for what it allows rather than for what it disables, so it reads
    # honestly in a systemd unit somebody finds two years from now.
    run.add_argument(
        "--allow-schema-drift",
        action="store_true",
        help="start even when the database has not had this version's migrations",
    )
    run.add_argument(
        "--supervise",
        action="store_true",
        help="start again when `!restart` stops the bot, instead of exiting",
    )

    init = sub.add_parser("init", help="create a bot instance directory for one game server")
    init.add_argument("directory", help="where the instance lives, e.g. /srv/cod4_1/b3")
    init.add_argument("--name", default="b3", help="instance name, used in logs and the unit file")
    # `choices` so a typo is refused here, with the valid set printed, instead of reaching a config
    # file. `metavar` keeps 29 ids out of the usage line; argparse still lists them on an error.
    init.add_argument(
        "--game",
        default="cod4",
        choices=sorted(PROFILES),
        metavar="GAME",
        help="parser id (default: cod4); see `b3 games`",
    )
    init.add_argument("--host", default="127.0.0.1", help="game server address")
    init.add_argument("--port", type=int, default=28960, help="game server RCON port")
    init.add_argument("--rcon-password", default="", help="RCON password")
    init.add_argument("--game-log", default="games_mp.log", help="path or ftp/sftp/http URL")
    init.add_argument(
        "--command-file",
        default="",
        help="altitude only: the file the game server reads commands from "
        "(default: command.txt beside the game log)",
    )
    init.add_argument("--database", default="sqlite:///b3.sqlite", help="SQLAlchemy URL")
    init.add_argument("--shared-plugins-dir", help="plugin pool shared with other instances")
    init.add_argument(
        "--no-geoip",
        action="store_true",
        help="skip the IP-to-country database check; the copy bundled with b3 is used instead",
    )
    init.add_argument("--service", action="store_true", help="also write a systemd unit file")
    init.add_argument("--service-user", default="b3", help="user the systemd unit runs as")
    init.add_argument("--force", action="store_true", help="overwrite an existing config")
    # The default when no --game is given and there is somebody to ask: `b3 init` is the first
    # command a new operator runs, and taking flags they have not read yet is backwards.
    init.add_argument(
        "--interactive",
        action="store_true",
        help="ask the questions instead of taking flags (the default when --game is not given)",
    )
    init.add_argument(
        "--no-interactive",
        dest="interactive",
        action="store_false",
        help="never ask; use the flags and their defaults",
    )
    init.set_defaults(interactive=None)
    sub.add_parser("doctor", help="check this install before starting it for the first time")
    probe = sub.add_parser(
        "probe",
        help="show what this server actually says, and which of our assumptions fit it (read-only)",
    )
    probe.add_argument(
        "--lines",
        type=int,
        default=DEFAULT_LINES,
        help=f"how many log lines to check (default: {DEFAULT_LINES})",
    )
    probe.add_argument(
        "--cvar", default="sv_maxclients", help="which cvar to try reading (default: sv_maxclients)"
    )
    probe.add_argument(
        "--redact",
        action="store_true",
        help="mask addresses and ids, for pasting the output somewhere public",
    )
    comp = sub.add_parser(
        "completion", help="print what to add to your shell so tab completion works"
    )
    # `default=None` rather than `""`: argparse validates a *string* default against `choices`, so an
    # empty default would have to be a choice — and then the shell offers an empty candidate beside
    # the five real ones, which is a thing nobody can type and nobody can read.
    comp.add_argument(
        "shell",
        nargs="?",
        default=None,
        choices=SHELLS,
        metavar="SHELL",
        help=f"one of: {', '.join(SHELLS)} (default: guessed from $SHELL)",
    )

    ver = sub.add_parser("version", help="print this version and the latest released one")
    ver.add_argument(
        "--refresh",
        action="store_true",
        help="ask the remote now instead of using the answer from the last week",
    )

    sub.add_parser("games", help="list the game titles this bot can read")
    sub.add_parser("plugins", help="list every plugin available here, and which this server runs")
    replay = sub.add_parser("replay", help="replay a recorded log file offline")
    replay.add_argument("logfile", help="path to a game log to replay")

    db = sub.add_parser("db", help="database migrations")
    db.add_argument("action", choices=["upgrade", "current", "stamp", "head"])
    db.add_argument("--revision", default="head").completer = (  # type: ignore[attr-defined]
        completion.revisions
    )

    update = sub.add_parser("update", help="check for a newer b3 and install it")
    update.add_argument(
        "--check",
        action="store_true",
        help="ask and print the answer; change nothing. Exits 1 when an update exists, so a cron "
        "job can mail you",
    )
    update.add_argument(
        "--to", default="", metavar="TAG", help="install this tag — also how to roll back"
    )
    update.add_argument("-y", "--yes", action="store_true", help="do not ask before installing")

    imp = sub.add_parser("import-db", help="import a legacy B3 database into this one")
    imp.add_argument("source_url", help="SQLAlchemy URL of the legacy DB (e.g. sqlite:///old.db)")

    icfg = sub.add_parser(
        "import-config", help="convert a classic B3 config directory into this one's YAML"
    )
    icfg.add_argument("source_dir", help="the classic install's conf/ directory (holds b3.xml)")
    icfg.add_argument(
        "-o", "--out", default=".", help="where to write the YAML (default: this directory)"
    )
    icfg.add_argument(
        "--dry-run",
        action="store_true",
        help="report what would be converted, and write nothing",
    )

    plug = sub.add_parser("plugin", help="install and manage plugins from git")
    plug_sub = plug.add_subparsers(dest="plugin_cmd", required=True)

    p_install = plug_sub.add_parser("install", help="install a plugin from a git repository")
    p_install.add_argument("spec", help="repo, optionally pinned: owner/repo@v1.2.0")
    p_install.add_argument("--ref", help="tag or branch to install (overrides any @ref in spec)")
    p_install.add_argument(
        "--disabled", action="store_true", help="add to the config, but do not run it"
    )
    p_install.add_argument(
        "--no-enable", action="store_true", help="install the files only; do not touch the config"
    )
    p_install.add_argument("--force", action="store_true", help="reinstall if already present")
    p_install.add_argument("-y", "--yes", action="store_true", help="skip the confirmation prompt")
    p_install.add_argument(
        "--shared",
        action="store_true",
        help="install into bot.shared_plugins_dir, the pool every bot on this machine can use",
    )

    plug_sub.add_parser("list", help="list installed plugins")

    p_enable = plug_sub.add_parser(
        "enable", help="run an already-installed plugin on this server (no download)"
    )
    p_enable.add_argument("name").completer = completion.plugins  # type: ignore[attr-defined]
    p_enable.add_argument(
        "--disabled", action="store_true", help="add it to the config but leave it inert"
    )

    p_disable = plug_sub.add_parser(
        "disable", help="stop running a plugin here; its files stay for other servers"
    )
    p_disable.add_argument("name").completer = completion.plugins  # type: ignore[attr-defined]

    p_update = plug_sub.add_parser("update", help="move an installed plugin to a newer ref")
    p_update.add_argument("name").completer = completion.plugins  # type: ignore[attr-defined]
    p_update.add_argument("--ref", help="tag or branch (default: highest semver tag)")
    p_update.add_argument("--shared", action="store_true", help="act on the shared pool")

    p_remove = plug_sub.add_parser("remove", help="uninstall a plugin")
    # Installed only, unlike enable/disable: `remove` works on the pool and refuses a name that was
    # never installed, so offering a bundled one would be offering what the command exists to reject.
    p_remove.add_argument("name").completer = completion.installed  # type: ignore[attr-defined]
    p_remove.add_argument(
        "--keep-files", action="store_true", help="deactivate but leave the files on disk"
    )
    p_remove.add_argument("--shared", action="store_true", help="act on the shared pool")

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()

    # Before parse_args, and only when the shell is asking: argcomplete reads the parser, writes its
    # candidates to file descriptor 8 and exits. With the package absent this is a no-op, which is why
    # it is an optional dependency rather than a requirement — completion is a convenience, and a bot
    # that will not start without it would be a poor trade.
    _autocomplete(parser)
    args = parser.parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    try:
        return _dispatch(args)
    finally:
        # After the command, never before it: whatever somebody ran `b3` for is done and printed by
        # now, so a line about a new release cannot delay it or come out in the middle of it.
        _mention_update(args)


def _dispatch(args: argparse.Namespace) -> int:
    """Run the command that was asked for. Split from `main` so the update line comes after it."""
    from b3.config.schema import ConfigError
    from b3.parsers.games import UnknownGameError
    from b3.runtime.bot import MissingServerModError, WrongGameError

    # `init` is the command you run when there is no config yet, `games` is pure reference, and
    # `completion` prints a line for a shell — none of the three must need a config to work. The last
    # one especially: an operator sets up tab completion once, from wherever they happen to be
    # standing, and having it ask for a config file would be the one thing that makes it useless.
    if args.cmd == "init":
        return _run_init(args)
    if args.cmd == "games":
        return _run_games()
    if args.cmd == "completion":
        return _run_completion(args.shell or "")
    # Converting a classic config is what you do *before* there is one to load, so it joins `init`
    # here rather than below. Requiring the file it exists to produce would be a fine joke.
    if args.cmd == "import-config":
        return _run_import_config(args)
    # `version` joins them: "which version am I running" is a question asked *about* an install that
    # is not working, which is the moment its config is least likely to load.
    if args.cmd == "version":
        return _run_version(args.config, args.refresh)

    config = load_config(args.config)
    conf_dir = Path(args.config).resolve().parent  # base for @conf tokens in plugin config paths

    try:
        if args.cmd == "doctor":
            return _run_doctor(config, conf_dir)
        if args.cmd == "probe":
            return _run_probe(config, conf_dir, args.lines, args.cvar, args.redact)
        if args.cmd == "run":
            if args.supervise:
                return _supervise()
            return asyncio.run(
                _run_live(
                    config,
                    conf_dir,
                    args.config,
                    allow_schema_drift=args.allow_schema_drift,
                )
            )
        elif args.cmd == "replay":
            asyncio.run(_run_replay(config, args.logfile, conf_dir, args.config))
        elif args.cmd == "plugins":
            return _run_plugins(config, conf_dir)
        elif args.cmd == "db":
            _run_db(config, args.action, args.revision)
        elif args.cmd == "update":
            return _run_update(config, args.check, args.to, args.yes)
        elif args.cmd == "import-db":
            _run_import(config, args.source_url)
        elif args.cmd == "plugin":
            return _run_plugin(config, args, Path(args.config), conf_dir)
    except (UnknownGameError, ConfigError, MissingServerModError, WrongGameError) as exc:
        # A one-line refusal beats a traceback: these are mistakes in their config, not crashes.
        # A missing server-side mod is the same kind of thing: an install job, with the command to
        # run in the message. `server.game` naming a different title from the one the server is
        # running is the same again, and the fix is one word in the file.
        logging.error("%s", exc)
        return 1
    return 0


def _run_init(args: argparse.Namespace) -> int:
    """`b3 init <dir>` — scaffold one game server's instance directory."""
    directory = Path(args.directory).resolve()
    answers = None
    if _should_ask(args):
        from b3.core import wizard

        try:
            answers = wizard.ask(directory, defaults=_spec_from_flags(args, directory))
        except (EOFError, KeyboardInterrupt):
            # Ctrl-D or Ctrl-C part way through. Nothing has been written yet, which is the whole
            # reason the questions come before the file rather than after each answer.
            print("\nnothing written")
            return 1

    spec = answers.spec if answers is not None else _spec_from_flags(args, directory)
    return _create(args, spec, run_doctor=bool(answers and answers.run_doctor))


def _should_ask(args: argparse.Namespace) -> bool:
    """Whether to ask rather than take the flags.

    `--interactive` and `--no-interactive` are explicit. With neither, asking is the default when no
    `--game` was given *and* there is a terminal to ask at — a scripted `b3 init` with its flags in a
    Dockerfile must never stop and wait for somebody who is not there.
    """
    import sys

    if args.interactive is not None:
        return bool(args.interactive)
    if args.game:
        return False
    return sys.stdin.isatty() and sys.stdout.isatty()


def _spec_from_flags(args: argparse.Namespace, directory: Path) -> InstanceSpec:
    return InstanceSpec(
        directory=directory,
        name=args.name,
        game=args.game or "cod4",
        host=args.host,
        port=args.port,
        rcon_password=args.rcon_password,
        game_log=args.game_log,
        database=args.database,
        shared_plugins_dir=args.shared_plugins_dir,
        command_file=args.command_file,
    )


def _create(args: argparse.Namespace, spec: InstanceSpec, *, run_doctor: bool) -> int:
    import sys

    from b3.core.instance import InstanceError, create_instance

    examples = Path(__file__).resolve().parent.parent.parent / "examples"
    try:
        written = create_instance(
            spec,
            examples_dir=examples if examples.is_dir() else None,
            service=args.service,
            python=sys.executable,
            user=args.service_user,
            force=args.force,
        )
    except InstanceError as exc:
        logging.error("%s", exc)
        return 1

    from b3.core.instance import _needs_command_file

    for path in written:
        print(f"wrote {path}")

    if not args.no_geoip:
        # A copy ships with this bot so geolocation works out of the box; this is what stops it being
        # the copy from whenever the release was cut. Optional, bounded and never fatal — see
        # `b3.core.geoipdata`. Nothing here can stop an instance being created.
        from b3.core.geoipdata import refresh_all

        # Into `~/.b3`, not this instance: every server on this machine reads the same answer about
        # the same addresses, and a copy each would be the same megabytes several times over.
        for said in refresh_all():
            print(said)

    print(f"\nnext:\n  b3 -c {spec.directory / 'b3.yaml'} run")
    if _needs_command_file(spec.game):
        # This family has no rcon password to set, and one path it cannot work without.
        print(f"  (check server.command_file — {spec.game} is driven by writing to that file)")
    elif not spec.rcon_password:
        print("  (set server.rcon_password first — it is empty)")
    if not run_doctor:
        return 0
    # Offered because the config being *written* is not the same as the server being reachable, and
    # the gap between those two is where a first evening goes.
    print()
    from b3.config.loader import load_config

    return _run_doctor(load_config(spec.directory / "b3.yaml"), spec.directory)


def _run_games() -> int:
    """`b3 games` — every valid `server.game`, grouped by the engine that reads it.

    Needs no config on purpose: it answers "what may I write in the config?", which is a question
    asked before there is one.
    """
    from b3.parsers.games import FILE_RCON_FAMILIES, PROFILES, PUSH_FAMILIES, by_family

    grouped = by_family()
    width = max(len(family) for family in grouped)
    for family, titles in grouped.items():
        # What the operator has to configure is the one thing a family decides for them, so it belongs
        # in the listing rather than only in the README: a log to point at, an rcon port that carries
        # the events instead, or a log *and* a command file for an engine with no rcon at all.
        if family in PUSH_FAMILIES:
            source = "events over rcon"
        elif family in FILE_RCON_FAMILIES:
            source = "log + command file"
        else:
            source = "reads a game log"
        print(f"{family:<{width}}  {source:<18}  {'  '.join(titles)}")
    print(f"\n{len(PROFILES)} titles. Set one as `server.game` in the config, or `b3 init --game`.")
    return 0


def _run_plugins(config: Config, conf_dir: Path | None) -> int:
    """`b3 plugins` — the three places a plugin can come from, and what this server runs.

    `b3 plugin list` covers the installed pools only; this is the whole set, which is what an
    operator needs to know what a name in the config may refer to.
    """
    import pkgutil

    import b3.plugins

    from b3.core import plugininstall as pi
    from b3.core.pluginmgr import BUILTIN_PACKAGE

    bundled = sorted(m.name for m in pkgutil.iter_modules(b3.plugins.__path__))
    print(f"bundled ({BUILTIN_PACKAGE}, no install needed):")
    print(f"  {'  '.join(bundled) if bundled else '(none)'}")

    pools = [("this server", pi.installed_plugins_dir(config.bot.plugins_dir, conf_dir))]
    if config.bot.shared_plugins_dir:
        shared = pi.installed_plugins_dir(config.bot.shared_plugins_dir, conf_dir)
        if shared != pools[0][1]:
            pools.append(("shared pool", shared))
    for label, directory in pools:
        records = pi.read_lockfile(directory)
        print(f"\ninstalled, {label} ({directory}):")
        if not records:
            print("  (none)")
        for rec in sorted(records.values(), key=lambda r: r.name):
            print(f"  {rec.name:<20} {rec.version:<10} {rec.ref}")

    print("\nenabled in this config:")
    if not config.plugins:
        print("  (none)")
    for entry in config.plugins:
        note = "  [disabled: loaded but inert]" if entry.disabled else ""
        print(f"  {entry.name:<20} {entry.module or f'{BUILTIN_PACKAGE}.{entry.name}'}{note}")
    return 0


def _run_probe(config: Config, conf_dir: Path | None, lines: int, cvar: str, hide: bool) -> int:
    """`b3 probe` — the raw truth about this server, for pasting back to whoever asked.

    Always exits 0: this reports, it does not judge. `b3 doctor` is the command with a verdict.
    """
    from b3.core.probe import run_probe

    # The checks talk to things, which is chatty, and the report *is* the output here.
    for noisy in ("b3.net.logsource", "b3.net.rcon"):
        logging.getLogger(noisy).setLevel(logging.ERROR)

    for line in run_probe(config, conf_dir, lines=lines, cvar=cvar, hide=hide):
        print(line)
    return 0


def _run_doctor(config: Config, conf_dir: Path | None) -> int:
    """`b3 doctor` — say what is wrong with this install, before it is anyone's evening."""
    from b3.core.doctor import Status, run_checks

    # The checks connect to things, which is chatty. The report is the output here, not the log.
    for noisy in ("alembic", "b3.core.plugininstall", "b3.net.logsource"):
        logging.getLogger(noisy).setLevel(logging.WARNING)

    marks = {Status.OK: "  ok  ", Status.WARN: " warn ", Status.FAIL: " FAIL "}
    checks = run_checks(config, conf_dir, check_update=True)
    width = max(len(c.name) for c in checks)
    for check in checks:
        print(f"[{marks[check.status]}] {check.name:<{width}}  {check.detail}")
        if check.hint and check.status is not Status.OK:
            print(f"{'':>{width + 11}}-> {check.hint}")

    failed = [c for c in checks if c.failed]
    warned = [c for c in checks if c.status is Status.WARN]
    print()
    if failed:
        print(f"{len(failed)} problem(s) to fix before this bot will work properly.")
        return 1
    if warned:
        print(f"ready to run, with {len(warned)} thing(s) worth a look.")
        return 0
    print("everything checks out. Start it with `b3 run`.")
    return 0


def _refuse_on_schema_drift(config: Config, config_path: str) -> bool:
    """True when the bot must not start because the database is behind the code.

    Running half-migrated is worse than refusing: the failure is a column that is not there, which
    surfaces as one feature behaving oddly rather than as anything anybody would connect to an
    upgrade. Every other operator mistake in this project is treated the same way — see the plugin
    loader's fatal-vs-tolerated rule.

    Only *behind* refuses. A database ahead of this code, a database that cannot be reached, and one
    with no stamp at all are all warnings: the first is somebody else's newer bot, the second is
    already reported by everything that touches the database, and the third is a schema built by
    hand, which is unusual but not this command's business to veto.
    """
    from b3.storage import migrate

    state = migrate.schema_state(config.bot.database)
    if state.ahead:
        logging.warning("database %s", state.describe())
        logging.warning(
            "-> a newer bot has migrated this database; this one may quietly stop populating "
            "new columns"
        )
        return False
    if not state.behind:
        return False
    logging.error("database %s", state.describe())
    logging.error("-> run: b3 -c %s db upgrade", config_path or "b3.yaml")
    logging.error("-> or start with --allow-schema-drift if you know this database is fine")
    return True


def _run_db(config: Config, action: str, revision: str) -> None:
    from b3.storage import migrate

    url = config.bot.database
    if action == "upgrade":
        # `command.upgrade` succeeds silently whether it applied five migrations or none, which is
        # indistinguishable from doing nothing — and "did I remember to run it?" is the question.
        result = migrate.upgrade_reporting(url, revision)
        logging.info("database %s", result.describe())
    elif action == "stamp":
        migrate.stamp(url, revision)
        logging.info("database stamped at %s", migrate.current_revision(url))
    elif action == "current":
        logging.info("current revision: %s", migrate.current_revision(url))
    elif action == "head":
        logging.info("head revision: %s", migrate.head_revision(url))


def _run_update(config: Config, check_only: bool, to: str, yes: bool) -> int:
    """`b3 update` — see b3.core.selfupdate for why this exists at all after deleting the classic's.

    Exit codes are chosen for scripting: `--check` answers 1 when an update exists, so a cron job can
    mail its output; anything that went wrong is 2, so "there is an update" and "the check failed"
    cannot be confused by a script.
    """
    import subprocess

    from b3.core import selfupdate

    remote = config.bot.update_remote.strip()
    if not remote:
        print("no update remote is configured (bot.update_remote is empty)")
        return 2
    info = selfupdate.check(remote)
    print(info.describe())
    if info.error:
        return 2
    if check_only:
        return 1 if info.available else 0
    tag = to.strip() or info.latest
    if not tag:
        return 2
    if not to and not info.available:
        print("nothing to install; name a tag with --to to install one anyway")
        return 0
    if selfupdate.in_container():
        # pip in the running environment is the wrong operation here: the image *is* the version.
        print("this is a container — pull a new image rather than updating in place")
        return 2
    command = selfupdate.install_command(remote, tag)
    print(f"installing {tag}: {' '.join(command)}")
    # Said before anything happens, because it is the surprising part: one code install serves every
    # instance on the machine, so this updates all of them at once.
    print("this updates every bot instance using this Python environment")
    if not yes:
        answer = input("go ahead? [y/N] ").strip().lower()
        if answer not in ("y", "yes"):
            print("nothing installed")
            return 0
    result = subprocess.run(command, check=False)
    if result.returncode != 0:
        print(f"pip exited {result.returncode}; nothing has changed in the running bot")
        return 2
    # Never in place: files have changed, and the change takes effect on the next start. And a new
    # version may add a migration, which §4.8's check will refuse to start without.
    print(f"installed {tag}. Restart each bot, then run `b3 -c <config> db upgrade` for each one.")
    return 0


def _update_settings(config_path: str) -> tuple[str, bool]:
    """(remote, may-we-ask) for a command that has no `Config` in its hands.

    `b3 version` and the line printed after a command both run where there may be no config at all —
    or a broken one, since "the config does not parse" is a thing somebody runs `b3 version` to help
    them debug. Either way the answer is the schema's own defaults rather than a traceback.
    """
    from b3.config.schema import BotConfig

    defaults = BotConfig()
    if not Path(config_path).is_file():
        return defaults.update_remote, defaults.update_check
    try:
        config = load_config(config_path)
    except Exception:  # noqa: BLE001 - see the docstring: anything at all here means "the defaults"
        # Broad on purpose, and this is the one place in the CLI where that is right: a YAML syntax
        # error, a schema violation, an unreadable file, a path that is a directory. Whatever it is,
        # the caller is printing a version number or a one-line notice, and neither is worth a
        # traceback about a config that some *other* command will report properly.
        return defaults.update_remote, defaults.update_check
    return config.bot.update_remote, config.bot.update_check


def _run_version(config_path: str, refresh: bool) -> int:
    """`b3 version` — which version this is, and which is the newest published.

    Both, because either alone is half an answer: a number nobody can compare to anything, or a
    release you cannot tell you already have. It exits **0** whatever it finds, unlike
    `b3 update --check`: a command somebody types to read a version number must not fail a script
    that runs it merely because there is a release out.
    """
    from b3.core import selfupdate

    print(f"b3 {__version__}")
    remote, enabled = _update_settings(config_path)
    if not enabled or not remote.strip():
        print("latest release: not checked (update checking is off)")
        return 0
    # Asked at most once a week unless `--refresh` says now, and remembered for whatever asks next.
    info = selfupdate.cached_check(remote, interval=0.0 if refresh else selfupdate.NOTICE_INTERVAL)
    if info.error:
        print(f"latest release: unknown ({info.error})")
        return 0
    print(f"latest release: {info.latest or 'none published yet'}")
    if info.available:
        print(f"run `b3 update` to install {info.latest}")
    return 0


def _mention_update(args: argparse.Namespace) -> None:
    """The line after a command, when a newer release exists. Never in the way of the command.

    Three rules keep this from becoming the thing people mute. It **reads a remembered answer** —
    at most once a week does any command pay for a `git ls-remote`, with a few seconds' timeout, and
    it happens *after* the command has done its work and printed it. It goes to **stderr**, so a
    `b3 games` piped into something else is unaffected. And it says nothing at all unless there is
    an update: being current is not news, and a failed check is not the business of somebody who ran
    `b3 plugins`.

    Only for a terminal. A cron job that wants this asks for it with `b3 update --check`, whose exit
    code is designed for exactly that, and does not want a surprise line in its mail.
    """
    from b3.core import selfupdate

    if args.cmd in NO_UPDATE_NOTICE or not selfupdate.notices_wanted():
        return
    if not sys.stderr.isatty():
        return
    remote, enabled = _update_settings(getattr(args, "config", ""))
    if not enabled or not remote.strip():
        return
    line = selfupdate.notice(selfupdate.cached_check(remote))
    if line:
        print(line, file=sys.stderr)


def _run_plugin(
    config: Config, args: argparse.Namespace, config_path: Path, conf_dir: Path | None
) -> int:
    """`b3 plugin install|list|update|remove` — see b3.core.plugininstall for the policies."""
    from b3.core import plugininstall as pi

    plugins_dir = pi.installed_plugins_dir(config.bot.plugins_dir, conf_dir)
    shared_dir = (
        pi.installed_plugins_dir(config.bot.shared_plugins_dir, conf_dir)
        if config.bot.shared_plugins_dir
        else None
    )
    if getattr(args, "shared", False):
        if shared_dir is None:
            logging.error(
                '--shared needs bot.shared_plugins_dir set in %s (e.g. "@home/plugins")',
                config_path,
            )
            return 1
        plugins_dir = shared_dir
    try:
        if args.plugin_cmd == "install":
            plan = pi.plan_install(args.spec, ref=args.ref)
            print(f"install {plan.url} at {plan.ref} into {plugins_dir}")
            print(
                "note: a plugin runs in-process with full access to your database and server; "
                "only install repositories you trust."
            )
            if not args.yes and not _confirm("proceed?"):
                print("aborted")
                return 1
            record = pi.install(
                args.spec,
                plugins_dir=plugins_dir,
                config_path=config_path,
                conf_dir=conf_dir,
                ref=args.ref,
                enable=not args.no_enable,
                disabled=args.disabled,
                force=args.force,
            )
            print(f"installed {record.name} {record.version} ({record.ref} @ {record.commit[:8]})")
            if args.no_enable:
                print(f"not activated; add it yourself:\n  - name: {record.name}")
                print(f"    module: {record.entry_point}")
            else:
                print(f"activated in {config_path}; restart b3 to load it")
        elif args.plugin_cmd == "enable":
            search = [plugins_dir] if shared_dir is None else [plugins_dir, shared_dir]
            record = pi.enable(
                args.name,
                plugins_dirs=search,
                config_path=config_path,
                conf_dir=conf_dir,
                disabled=args.disabled,
            )
            print(f"enabled {record.name} {record.version} in {config_path}; restart b3 to load it")
        elif args.plugin_cmd == "disable":
            pi.disable(args.name, config_path=config_path)
            print(f"disabled {args.name} in {config_path}; its files were left in place")
        elif args.plugin_cmd == "list":
            pools = [("this server", plugins_dir)]
            if shared_dir is not None and shared_dir != plugins_dir:
                pools.insert(0, ("shared", shared_dir))
            for label, directory in pools:
                records = pi.read_lockfile(directory)
                print(f"[{label}] {directory}")
                if not records:
                    print("  (none)")
                for rec in sorted(records.values(), key=lambda r: r.name):
                    print(
                        f"  {rec.name:<20} {rec.version:<10} {rec.ref:<15} "
                        f"{rec.commit[:8]}  {rec.url}"
                    )
        elif args.plugin_cmd == "update":
            record = pi.update(args.name, plugins_dir=plugins_dir, ref=args.ref, conf_dir=conf_dir)
            print(f"updated {record.name} to {record.version} ({record.ref} @ {record.commit[:8]})")
        elif args.plugin_cmd == "remove":
            pi.remove(
                args.name,
                plugins_dir=plugins_dir,
                config_path=config_path,
                keep_files=args.keep_files,
            )
            print(f"removed {args.name}")
    except pi.PluginInstallError as exc:
        logging.error("%s", exc)
        return 1
    return 0


def _confirm(question: str) -> bool:
    try:
        return input(f"{question} [y/N] ").strip().lower() in ("y", "yes")
    except EOFError:  # non-interactive shell
        return False


def _run_import_config(args: argparse.Namespace) -> int:
    """`b3 import-config` — a classic conf/ directory into this one's YAML, plus what it could not do.

    The report is the feature. Anything unconvertible is named with what to do instead, so the part
    a person still has to do is a finite list rather than an unknown.
    """
    from b3.legacy.config import convert_config_tree

    source = Path(args.source_dir)
    if not source.is_dir():
        logging.error(
            "%s is not a directory; point this at the classic install's conf/ folder", source
        )
        return 1
    report = convert_config_tree(source, Path(args.out), write=not args.dry_run)
    if not report.files:
        logging.error("no b3.xml or plugin_*.ini/.xml found in %s", source)
        return 1
    print(report.render())
    if args.dry_run:
        print("\n(--dry-run: nothing was written)")
    return 0


def _run_import(config: Config, source_url: str) -> None:
    from b3.legacy import import_legacy_database
    from b3.storage.store import SqlAlchemyStorage

    target = SqlAlchemyStorage(config.bot.database)
    report = import_legacy_database(source_url, target)
    target.close()
    logging.info("import complete: %s", report.summary())


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
